#+TITLE: MongoDB - The Complete Developer's Guide, Udemy - Notes
#+AUTHOR: Alexandre Gressier
#+DATE: <2019-11-17 Sun>

Most recent version at the time of writing: 4.2.1

* 2. What is MongoDB?

MongoDB is database
The enteprise backing MongoDB is also called MongoDB

The name is stemming from the word humongous
-> Meant to store a lot of data

MongoDB's server provides multiple databases
Collections are stored inside a database
Documents are store inside collections

Inside a collection, you are schemaless

You can structure your data in MongoDB though

Documents are stored in the JSON format
A JSON document is delimited by `{}`

A key is composed of a name and a value separated by a colon
The name must be surrounded by `""`
Keys names are often referred to as simply keys
Values can be strings, numbers, booleans, lists, and even nested data (i.e., embedded documents)
-> Enables you to create complex data and store it in a single document (which is more efficient that resolving relation in a RDB)

Behind the scenes, MongoDB converts the JSON into a binary format called BSON (more efficient to query and store)

MongoDB is flexible, performant, and usable


* 4. The Key MongoDB Characteristics (and how they differ from SQL Databases)

Schemaless can lead to messy data b/c it your responsability to work with clean data

You also work with less relations in MongoDB b/c you store data together

It does not need to merge data most of the time
-> Improves performance


* 5. Understanding the MongoDB Ecosystem

The MongoDB enterprise provides:
- The MongoDB database
  - Self-managed / Enterprise
  - Tools: CloudManager / OpsManager
- Atlas: MongoDB on the Cloud
- Mobile
- GUI: compass
- Business Intelligence connectors
- MongoDB Charts

New offering: Stitch (serverless backend solution)
-> A bit unrelated to the MongoDB database
- Serverless Query API
- Serverless functions
- Database triggers
- Real-Time sync


* 6. Installing MongoDB

MongoDB runs on all OSs

Community server VS Enterprise server

MongoDB installation directory contains a bin/ directory that should be added to path

MongoDB packages

- mongodb-org: A metapackage that will automatically install the four component
  packages listed below.

- mongodb-org-server: Contains the mongod daemon, associated init script, and a
  configuration file (/etc/mongod.conf). You can use the initialization script
  to start mongod with the configuration file. For details, see Run MongoDB
  Community Edition.

- mongodb-org-mongos: Contains the mongos daemon.

- mongodb-org-shell: Contains the mongo shell.

- mongodb-org-tools: Contains the following MongoDB tools: mongoimport bsondump,
  mongodump, mongoexport, mongofiles, mongorestore, mongostat, and mongotop.

`mongo` is the name of the client shell that connects to the daemon

#+BEGIN_SRC bash
  $ mongo --host 'mongodb://127.0.0.1:27017' --username root --password example
#+END_SRC

Stopping the MongoDB server service on Windows: `net stop MongoDB`

Starting the MongoDB server: `mongod`
IMPORTANT: on Linux and macOS, the default data directory is `/data/db`
-> Or `mongod --dbpath 'specialDir'` to specify it
-> On Windows, `data/db` is inside the installation directory

The data directory mainly contains .wt (WiredTiger) files

#+BEGIN_QUOTE
  Catalina has a surprise change: it won't allow changes to the root directory
#+END_QUOTE


* 8. Time To Get Started!
  
Authenticate:
$ mongo -u root -p example

> cls
Clear the screen

> show dbs
Show databases

3 default dbs that store metadata:
- admin
- config
- local

> use shop
Connect to the database 'shop' and create it if unavailable

db refers to the current database
> db
shop
By default, you are in a unknown database called test

> db.products.insertOne({name: "A book", price: 12.99})
Create the shop db and the products collection by inserting one document in it

Note: in the shell, `""` can be omitted for keys (will be added when stored)

MongoDB automatically creates a unique ID for any document inserted

> db.products.find()
Find all the documents in the collection

> db.products.pretty()
Prettify the output

The order of the keys in the inserted document is unchanged


* 9. Shell vs Drivers

The Mongo shell is language agnostic (/neutral ground/)

To work with a specific language, you must use a driver:
https://docs.mongodb.com/ecosystem/drivers/

You use the same commands as in the shell when using a driver
