name: dart_sandbox
description: A sample command-line sandbox application to play with Dart.
version: 0.1.0
homepage: https://github.com/alexandregressier/notes/dart-in-action

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
